### ISSUE TITLE
--enable-btyacc: function _lookup_arg_cache is missing

### ISSUE THREAD

**Issue by zosrothko** [AaronNGray/byacc#2]
Hi

When enabling the btyacc skeleton, the function _lookup_arg_cache is missing is missing. Do not know how to fix this.

**Comment by AaronNGray** [comment]
Hi, I just imported BYACC to look at the code on my tablet as I am working on my own cross platform modern C++ parser generator. Never got round to building BYACC IIRC. You can either fork this repo and add your patches, or submit two separate patches one for VS2015 with VS2015 solution and project as a separate directory so it does not pollute the existing Unix platform code and another for the "typo" please. Another idea would to use CMake for cross platform solutions. Regarding the runtime it is horrible old style code and it would take too long to work out a cross platform port !
